// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.14.0
// source: dm/action.proto

package dm

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// 数据上报
type Action struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Action:
	//	*Action_Heartbeat
	//	*Action_ChangeAccount
	Action isAction_Action `protobuf_oneof:"action"`
}

func (x *Action) Reset() {
	*x = Action{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dm_action_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_dm_action_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_dm_action_proto_rawDescGZIP(), []int{0}
}

func (m *Action) GetAction() isAction_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func (x *Action) GetHeartbeat() *Heartbeat {
	if x, ok := x.GetAction().(*Action_Heartbeat); ok {
		return x.Heartbeat
	}
	return nil
}

func (x *Action) GetChangeAccount() *ChangeAccount {
	if x, ok := x.GetAction().(*Action_ChangeAccount); ok {
		return x.ChangeAccount
	}
	return nil
}

type isAction_Action interface {
	isAction_Action()
}

type Action_Heartbeat struct {
	// 心跳消息
	Heartbeat *Heartbeat `protobuf:"bytes,1,opt,name=heartbeat,proto3,oneof"`
}

type Action_ChangeAccount struct {
	// 修改云视讯账号
	ChangeAccount *ChangeAccount `protobuf:"bytes,2,opt,name=changeAccount,proto3,oneof"`
}

func (*Action_Heartbeat) isAction_Action() {}

func (*Action_ChangeAccount) isAction_Action() {}

var File_dm_action_proto protoreflect.FileDescriptor

var file_dm_action_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x64, 0x6d, 0x2f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0b, 0x74, 0x72, 0x69, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x2e, 0x64, 0x6d, 0x1a, 0x12,
	0x64, 0x6d, 0x2f, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x17, 0x64, 0x6d, 0x2f, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8e, 0x01, 0x0a, 0x06,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x36, 0x0a, 0x09, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62,
	0x65, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x74, 0x72, 0x69, 0x63,
	0x6c, 0x61, 0x73, 0x73, 0x2e, 0x64, 0x6d, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61,
	0x74, 0x48, 0x00, 0x52, 0x09, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x12, 0x42,
	0x0a, 0x0d, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x74, 0x72, 0x69, 0x63, 0x6c, 0x61, 0x73, 0x73,
	0x2e, 0x64, 0x6d, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x48, 0x00, 0x52, 0x0d, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x42, 0x08, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x1c, 0x0a, 0x0f,
	0x63, 0x6f, 0x6d, 0x2e, 0x74, 0x72, 0x69, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x2e, 0x64, 0x6d, 0x50,
	0x01, 0x5a, 0x07, 0x2e, 0x2f, 0x64, 0x6d, 0x3b, 0x64, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_dm_action_proto_rawDescOnce sync.Once
	file_dm_action_proto_rawDescData = file_dm_action_proto_rawDesc
)

func file_dm_action_proto_rawDescGZIP() []byte {
	file_dm_action_proto_rawDescOnce.Do(func() {
		file_dm_action_proto_rawDescData = protoimpl.X.CompressGZIP(file_dm_action_proto_rawDescData)
	})
	return file_dm_action_proto_rawDescData
}

var file_dm_action_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dm_action_proto_goTypes = []interface{}{
	(*Action)(nil),        // 0: triclass.dm.Action
	(*Heartbeat)(nil),     // 1: triclass.dm.Heartbeat
	(*ChangeAccount)(nil), // 2: triclass.dm.ChangeAccount
}
var file_dm_action_proto_depIdxs = []int32{
	1, // 0: triclass.dm.Action.heartbeat:type_name -> triclass.dm.Heartbeat
	2, // 1: triclass.dm.Action.changeAccount:type_name -> triclass.dm.ChangeAccount
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_dm_action_proto_init() }
func file_dm_action_proto_init() {
	if File_dm_action_proto != nil {
		return
	}
	file_dm_heartbeat_proto_init()
	file_dm_change_account_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_dm_action_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Action); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_dm_action_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Action_Heartbeat)(nil),
		(*Action_ChangeAccount)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dm_action_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dm_action_proto_goTypes,
		DependencyIndexes: file_dm_action_proto_depIdxs,
		MessageInfos:      file_dm_action_proto_msgTypes,
	}.Build()
	File_dm_action_proto = out.File
	file_dm_action_proto_rawDesc = nil
	file_dm_action_proto_goTypes = nil
	file_dm_action_proto_depIdxs = nil
}
